var tt= [
    Player {
      username: 'gg',
      email: 'ii@gmail.com',
      cards: [ [Card], [Card] ],
      socket: Socket {
        nsp: [Namespace],
        server: [Server],
        adapter: [Adapter],
        id: 'JWvWz1cjjwx6Nnl8AAAC',
        client: [Client],
        conn: [Socket],
        rooms: [Object],
        acks: {},
        connected: true,
        disconnected: false,
        handshake: [Object],
        fns: [],
        flags: {},
        _rooms: [],
        _events: [Object: null prototype],
        _eventsCount: 10
      },
      currentCard: null,
      money: 1000,
      buyIns: 1,
      status: '',
      blindValue: 'Big Blind',
      dealer: false,
      allIn: false,
      goAgainStatus: false,
      debug: false,
      addCard: [Function (anonymous)],
      log: [Function (anonymous)],
      setStatus: [Function (anonymous)],
      setBlind: [Function (anonymous)],
      setDealer: [Function (anonymous)],
      getUsername: [Function (anonymous)],
      getEmail: [Function (anonymous)],
      getBuyIns: [Function (anonymous)],
      getMoney: [Function (anonymous)],
      getStatus: [Function (anonymous)],
      getBlind: [Function (anonymous)],
      getDealer: [Function (anonymous)],
      emit: [Function (anonymous)]
    },
    Player {
      username: 'kjhb',
      email: 'll@gmail.oocm',
      cards: [ [Card], [Card] ],
      socket: Socket {
        nsp: [Namespace],
        server: [Server],
        adapter: [Adapter],
        id: 'ilkWqVI8UR-gXcs7AAAD',
        client: [Client],
        conn: [Socket],
        rooms: [Object],
        acks: {},
        connected: true,
        disconnected: false,
        handshake: [Object],
        fns: [],
        flags: {},
        _rooms: [],
        _events: [Object: null prototype],
        _eventsCount: 10
      },
      currentCard: null,
      money: 3000,
      buyIns: 0,
      status: '',
      blindValue: '',
      dealer: true,
      allIn: false,
      goAgainStatus: false,
      debug: false,
      addCard: [Function (anonymous)],
      log: [Function (anonymous)],
      setStatus: [Function (anonymous)],
      setBlind: [Function (anonymous)],
      setDealer: [Function (anonymous)],
      getUsername: [Function (anonymous)],
      getEmail: [Function (anonymous)],
      getBuyIns: [Function (anonymous)],
      getMoney: [Function (anonymous)],
      getStatus: [Function (anonymous)],
      getBlind: [Function (anonymous)],
      getDealer: [Function (anonymous)],
      emit: [Function (anonymous)]
    },
    Player {
      username: 'ip',
      email: 'kk@gmail.com',
      cards: [ [Card], [Card] ],
      socket: Socket {
        nsp: [Namespace],
        server: [Server],
        adapter: [Adapter],
        id: 'NbqjlLEPHcCM6tb0AAAE',
        client: [Client],
        conn: [Socket],
        rooms: [Object],
        acks: {},
        connected: true,
        disconnected: false,
        handshake: [Object],
        fns: [],
        flags: {},
        _rooms: [],
        _events: [Object: null prototype],
        _eventsCount: 10
      },
      currentCard: null,
      money: 0,
      buyIns: 0,
      status: 'Their Turn',
      blindValue: 'Small Blind',
      dealer: false,
      allIn: false,
      goAgainStatus: false,
      debug: false,
      addCard: [Function (anonymous)],
      log: [Function (anonymous)],
      setStatus: [Function (anonymous)],
      setBlind: [Function (anonymous)],
      setDealer: [Function (anonymous)],
      getUsername: [Function (anonymous)],
      getEmail: [Function (anonymous)],
      getBuyIns: [Function (anonymous)],
      getMoney: [Function (anonymous)],
      getStatus: [Function (anonymous)],
      getBlind: [Function (anonymous)],
      getDealer: [Function (anonymous)],
      emit: [Function (anonymous)]
    }
  ]